//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au Ra.
        /// </summary>
        internal static string Au_Ra {
            get {
                return ResourceManager.GetString("Au_Ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop Autoturret.
        /// </summary>
        internal static string Bishop_Autoturret {
            get {
                return ResourceManager.GetString("Bishop_Autoturret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black chocobo.
        /// </summary>
        internal static string Black_Chocobo {
            get {
                return ResourceManager.GetString("Black_Chocobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Hands.
        /// </summary>
        internal static string Body_Hands {
            get {
                return ResourceManager.GetString("Body_Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Hands + Legs.
        /// </summary>
        internal static string Body_Hands_Legs {
            get {
                return ResourceManager.GetString("Body_Hands_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Hands + Legs + Feet.
        /// </summary>
        internal static string Body_Hands_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Hands_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Legs + Feet.
        /// </summary>
        internal static string Body_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbuncle.
        /// </summary>
        internal static string Carbuncle {
            get {
                return ResourceManager.GetString("Carbuncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceremony.
        /// </summary>
        internal static string Ceremony_Chocobo {
            get {
                return ResourceManager.GetString("Ceremony_Chocobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company.
        /// </summary>
        internal static string Company_Chocobo {
            get {
                return ResourceManager.GetString("Company_Chocobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draught.
        /// </summary>
        internal static string Draught_Chocobo {
            get {
                return ResourceManager.GetString("Draught_Chocobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ears.
        /// </summary>
        internal static string Ears {
            get {
                return ResourceManager.GetString("Ears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elezen.
        /// </summary>
        internal static string Elezen {
            get {
                return ResourceManager.GetString("Elezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eos.
        /// </summary>
        internal static string Eos {
            get {
                return ResourceManager.GetString("Eos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        internal static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint.
        /// </summary>
        internal static string Face_Paint {
            get {
                return ResourceManager.GetString("Face_Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garuda Egi.
        /// </summary>
        internal static string Garuda_Egi {
            get {
                return ResourceManager.GetString("Garuda_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        internal static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head + Body.
        /// </summary>
        internal static string Head_Body {
            get {
                return ResourceManager.GetString("Head_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlander.
        /// </summary>
        internal static string Highlander {
            get {
                return ResourceManager.GetString("Highlander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyur.
        /// </summary>
        internal static string Hyur {
            get {
                return ResourceManager.GetString("Hyur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ifrit Egi.
        /// </summary>
        internal static string Ifrit_Egi {
            get {
                return ResourceManager.GetString("Ifrit_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003F6400.
        /// </summary>
        internal static string Item_0 {
            get {
                return ResourceManager.GetString("Item_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002BA780.
        /// </summary>
        internal static string Item_1000 {
            get {
                return ResourceManager.GetString("Item_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04343700.
        /// </summary>
        internal static string Item_10000 {
            get {
                return ResourceManager.GetString("Item_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 042F4580.
        /// </summary>
        internal static string Item_10500 {
            get {
                return ResourceManager.GetString("Item_10500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 040B0C80.
        /// </summary>
        internal static string Item_11000 {
            get {
                return ResourceManager.GetString("Item_11000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02FFF500.
        /// </summary>
        internal static string Item_11500 {
            get {
                return ResourceManager.GetString("Item_11500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 036D4200.
        /// </summary>
        internal static string Item_12000 {
            get {
                return ResourceManager.GetString("Item_12000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0429E600.
        /// </summary>
        internal static string Item_12500 {
            get {
                return ResourceManager.GetString("Item_12500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03376880.
        /// </summary>
        internal static string Item_13000 {
            get {
                return ResourceManager.GetString("Item_13000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03440900.
        /// </summary>
        internal static string Item_13500 {
            get {
                return ResourceManager.GetString("Item_13500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04317D00.
        /// </summary>
        internal static string Item_14000 {
            get {
                return ResourceManager.GetString("Item_14000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0472A580.
        /// </summary>
        internal static string Item_14500 {
            get {
                return ResourceManager.GetString("Item_14500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0122DE80.
        /// </summary>
        internal static string Item_1500 {
            get {
                return ResourceManager.GetString("Item_1500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0373FE00.
        /// </summary>
        internal static string Item_15000 {
            get {
                return ResourceManager.GetString("Item_15000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04720980.
        /// </summary>
        internal static string Item_15500 {
            get {
                return ResourceManager.GetString("Item_15500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04FCD080.
        /// </summary>
        internal static string Item_16000 {
            get {
                return ResourceManager.GetString("Item_16000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 029B0500.
        /// </summary>
        internal static string Item_16500 {
            get {
                return ResourceManager.GetString("Item_16500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05030380.
        /// </summary>
        internal static string Item_17000 {
            get {
                return ResourceManager.GetString("Item_17000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05037800.
        /// </summary>
        internal static string Item_17500 {
            get {
                return ResourceManager.GetString("Item_17500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123DF00.
        /// </summary>
        internal static string Item_2000 {
            get {
                return ResourceManager.GetString("Item_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00035000.
        /// </summary>
        internal static string Item_2500 {
            get {
                return ResourceManager.GetString("Item_2500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0036D580.
        /// </summary>
        internal static string Item_3000 {
            get {
                return ResourceManager.GetString("Item_3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0216FD00.
        /// </summary>
        internal static string Item_3500 {
            get {
                return ResourceManager.GetString("Item_3500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01282D80.
        /// </summary>
        internal static string Item_4000 {
            get {
                return ResourceManager.GetString("Item_4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01167A80.
        /// </summary>
        internal static string Item_4500 {
            get {
                return ResourceManager.GetString("Item_4500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00648800.
        /// </summary>
        internal static string Item_500 {
            get {
                return ResourceManager.GetString("Item_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00109C80.
        /// </summary>
        internal static string Item_5000 {
            get {
                return ResourceManager.GetString("Item_5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005CF880.
        /// </summary>
        internal static string Item_5500 {
            get {
                return ResourceManager.GetString("Item_5500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002D4F80.
        /// </summary>
        internal static string Item_6000 {
            get {
                return ResourceManager.GetString("Item_6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002A200.
        /// </summary>
        internal static string Item_6500 {
            get {
                return ResourceManager.GetString("Item_6500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02811980.
        /// </summary>
        internal static string Item_7000 {
            get {
                return ResourceManager.GetString("Item_7000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01680A80.
        /// </summary>
        internal static string Item_7500 {
            get {
                return ResourceManager.GetString("Item_7500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0282B400.
        /// </summary>
        internal static string Item_8000 {
            get {
                return ResourceManager.GetString("Item_8000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 044D3B80.
        /// </summary>
        internal static string Item_8500 {
            get {
                return ResourceManager.GetString("Item_8500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 026F6480.
        /// </summary>
        internal static string Item_9000 {
            get {
                return ResourceManager.GetString("Item_9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 036BA000.
        /// </summary>
        internal static string Item_9500 {
            get {
                return ResourceManager.GetString("Item_9500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lalafell.
        /// </summary>
        internal static string Lalafell {
            get {
                return ResourceManager.GetString("Lalafell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legacy.
        /// </summary>
        internal static string Legacy_Chocobo {
            get {
                return ResourceManager.GetString("Legacy_Chocobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs + Feet.
        /// </summary>
        internal static string Legs_Feet {
            get {
                return ResourceManager.GetString("Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magitek.
        /// </summary>
        internal static string Magitek {
            get {
                return ResourceManager.GetString("Magitek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Hand.
        /// </summary>
        internal static string Main_Hand {
            get {
                return ResourceManager.GetString("Main_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Hand + Off Hand.
        /// </summary>
        internal static string Main_Off {
            get {
                return ResourceManager.GetString("Main_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midlander.
        /// </summary>
        internal static string Midlander {
            get {
                return ResourceManager.GetString("Midlander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005F4700.
        /// </summary>
        internal static string minionEXD {
            get {
                return ResourceManager.GetString("minionEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minions.
        /// </summary>
        internal static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miqo&apos;te.
        /// </summary>
        internal static string Miqote {
            get {
                return ResourceManager.GetString("Miqote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05044080.
        /// </summary>
        internal static string Modelchara_0 {
            get {
                return ResourceManager.GetString("Modelchara_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02883500.
        /// </summary>
        internal static string mountEXD {
            get {
                return ResourceManager.GetString("mountEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        internal static string Mounts {
            get {
                return ResourceManager.GetString("Mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Hand.
        /// </summary>
        internal static string Off_Hand {
            get {
                return ResourceManager.GetString("Off_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramuh Egi.
        /// </summary>
        internal static string Ramuh_Egi {
            get {
                return ResourceManager.GetString("Ramuh_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red_Baron {
            get {
                return ResourceManager.GetString("Red_Baron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings.
        /// </summary>
        internal static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roegadyn.
        /// </summary>
        internal static string Roegadyn {
            get {
                return ResourceManager.GetString("Roegadyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook Autoturret.
        /// </summary>
        internal static string Rook_Autoturret {
            get {
                return ResourceManager.GetString("Rook_Autoturret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selene.
        /// </summary>
        internal static string Selene {
            get {
                return ResourceManager.GetString("Selene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Crystal.
        /// </summary>
        internal static string Soul_Crystal {
            get {
                return ResourceManager.GetString("Soul_Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail.
        /// </summary>
        internal static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titan Egi.
        /// </summary>
        internal static string Titan_Egi {
            get {
                return ResourceManager.GetString("Titan_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twintania.
        /// </summary>
        internal static string Twintania {
            get {
                return ResourceManager.GetString("Twintania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Handed.
        /// </summary>
        internal static string Two_Handed {
            get {
                return ResourceManager.GetString("Two_Handed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string Waist {
            get {
                return ResourceManager.GetString("Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warsteed.
        /// </summary>
        internal static string Warsteed {
            get {
                return ResourceManager.GetString("Warsteed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White_Devil {
            get {
                return ResourceManager.GetString("White_Devil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrists.
        /// </summary>
        internal static string Wrists {
            get {
                return ResourceManager.GetString("Wrists", resourceCulture);
            }
        }
    }
}
